DEF NUM_PLAYER_NAMES EQU 3

;IF DEF(_RED)
DEF PLAYERNAME1 EQUS "RED"
DEF PLAYERNAME2 EQUS "ASH"
DEF PLAYERNAME3 EQUS "CHASE" ; was JACK

DEF RIVALNAME1 EQUS "BLUE"
DEF RIVALNAME2 EQUS "GARY"
DEF RIVALNAME3 EQUS "TRACE" ; was JOHN
;ENDC

; seynotes: Commented because I want it, uncomment these + the if above if you want original behavior
; IF DEF(_BLUE)
; DEF PLAYERNAME1 EQUS "BLUE"
; DEF PLAYERNAME2 EQUS "GARY"
; DEF PLAYERNAME3 EQUS "JOHN"

; DEF RIVALNAME1 EQUS "RED"
; DEF RIVALNAME2 EQUS "ASH"
; DEF RIVALNAME3 EQUS "JACK"
; ENDC

; seynotes: Girl protag names
DEF FPLAYERNAME1 EQUS "LEAF"
DEF FPLAYERNAME2 EQUS "GREEN"
DEF FPLAYERNAME3 EQUS "ELAINE"

; seynotes: Girl protag toggle
DEF BIT_PLAYER_GIRL EQU 0